# IN CLASS LAB EXERCISES - 01

#### Import NumPy package as np

In [1]:
import numpy as np

####  01.  Create an empty array of 20 0's and replace the 4th object with the number 5

In [2]:
# 4th object -> 3rd index
b = np.zeros(20)
b[3] = 5
b

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

--------

#### 02. Create an array of 20 1's and store it as a variable named array_master. Copy the same array into another variable named array_copy

In [3]:
array_master = np.ones(20)
print(array_master)
array_copy = array_master.copy()
print(array_copy)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


--------

#### 03.Create an array containing 30 1's and broadcast all the one's to the value 100

In [4]:
l_30 = np.ones(30)

In [27]:
l_30 * 100

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

----------------------------------------------------

#### 04. Create an array of integers starting from 21 until 31 and name it as array1

####  ---     Create an array of integers starting from 11 until 21 and name it array2

####  ---    Calculate the difference between array1 and array2

In [5]:
array1 = np.arange(21,31)
array2 = np.arange(11, 21)

array1 - array2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

---------------------------------------------

#### 05. Create an array of all even integers from 2 to 10 and name it a1

#### --   Create an array of all even integers from 22 to 30 and name it a2

####    a) Use the 2 arrays as rows and create a matrix [ Hint - Use stack function from numpy ]

In [6]:
a1 = np.arange(2, 11, 2)
a2 = np.arange(22, 31, 2)

print(np.vstack((a1, a2)))
print(np.vstack((a1, a2)).shape)

[[ 2  4  6  8 10]
 [22 24 26 28 30]]
(2, 5)


-----------------------

####  b) Use the 2 arrays as columns and create a matrix [ Hint - Use column_stack function from numpy ]

In [7]:
out = np.column_stack((a1, a2))
print(out, out.shape)

[[ 2 22]
 [ 4 24]
 [ 6 26]
 [ 8 28]
 [10 30]] (5, 2)


--------------

#### 06. Create a 5x6 matrix with values ranging from 0 to 29 and retrieve the value intersecting at 2nd row and 3rd column

In [8]:
out = np.arange(30).reshape(5,6)
print(out)
out[1][2]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


8

--------------------

#### 07. Create an identity matrix of shape 10x10 and replace the 0's with the value 21

In [9]:
diag = np.eye(10)

diag[ diag == 0 ] = 21
diag

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

--------------------

#### Use NumPy to generate a random set of 10 numbers between 0 and 1

#### 08. Display a boolean array output where all values > 0.2 are True, rest are marked as False

In [10]:
out = np.random.rand(10)
print(out > 0.2)


[ True  True False False  True False False  True  True  True]


-------------------

#### 09. Use NumPy to generate an array matrix of 5x2 random numbers sampled from a standard normal distribution

In [11]:
np.random.randn(5,2)

array([[ 1.87295579, -0.23292575],
       [-1.13432646, -0.54597426],
       [-0.1593149 ,  0.63079864],
       [ 0.865381  , -0.76413216],
       [ 0.97451346, -0.23343017]])

-----------------------------

#### 10. Create an array of 30 linearly spaced points between 0 and 100:

In [12]:
np.linspace(1,100,30)

array([  1.        ,   4.4137931 ,   7.82758621,  11.24137931,
        14.65517241,  18.06896552,  21.48275862,  24.89655172,
        28.31034483,  31.72413793,  35.13793103,  38.55172414,
        41.96551724,  45.37931034,  48.79310345,  52.20689655,
        55.62068966,  59.03448276,  62.44827586,  65.86206897,
        69.27586207,  72.68965517,  76.10344828,  79.51724138,
        82.93103448,  86.34482759,  89.75862069,  93.17241379,
        96.5862069 , 100.        ])

---------------------------

## Numpy Indexing and Selections

#### 11. Using the below given Matrix, generate the output for the below questions.

In [13]:
mat = np.arange(40).reshape(4,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

----------------

#### a) Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique

In [14]:
mat[-2:, :3]

array([[20, 21, 22],
       [30, 31, 32]])

In [15]:
mat[-2:][:,:3]

array([[20, 21, 22],
       [30, 31, 32]])

------

#### b) Retrieve the value 55 from the above matrix using index & selection technique

In [16]:
# Will be retrieving 55 here
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [17]:
mat[3,9]

39

--------------

#### c) Retrieve the values from the 3rd column in the above matrix

In [18]:
# 3rd column 2nd index
mat[:, 2]

array([ 2, 12, 22, 32])

---------------

#### d) Retrieve the values from the 4th row in the above matrix

In [19]:
mat[3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

-----------------

#### e) Retrieve values from the 2nd & 4th rows in the above matrix

In [20]:
# 2nd row 1st index
# 4th row 3rd index
mat[[1,3]]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

--------------

### Calculate the following values for the given matrix

#### a) Calculate sum of all the values in the matrix

In [21]:
np.sum(mat)

780

--------------

#### b) Calculate standard deviation of all the values in the matrix

In [22]:
np.std(mat)

11.543396380615196

------

#### c) Calculate the variance of all values in the matrix

In [23]:
np.var(mat)

133.25

-----------

#### d) Calculate the mean of all values in the matrix

In [24]:
np.mean(mat)

19.5

-------------

#### e) Retrieve the largest number from the matrix

In [25]:
np.max(mat)

39

--------------

#### f) Retrieve the smallest number from the matrix

In [26]:
np.min(mat)

0

-------

# -------------------------------- HAPPY LEARNING -------------------------------

--------------------------------