# TAKE HOME LAB EXERCISE - 01

-----------

In [1]:
import numpy as np

**(1). The value Range(0,10) ,  convert the list to `2D array`.**

In [2]:
lst = list(range(10))
lst = np.array(lst)
lst.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

-------------------------------------------------------------

**(2).Print or show only 3 decimal places of the numpy array `random_arr`**

In [3]:
random_arr = np.random.rand(2,3)

np.round(random_arr, 3)

array([[0.541, 0.328, 0.828],
       [0.231, 0.658, 0.868]])

----------------------------------

**(3).The number of items printed to be limit in python numpy array a to a maximum of 6 elements.**

   
     Intake : x = np.arange(15)
               array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
               
     Result : ([ 0,  1,  2, ..., 12, 13, 14])

In [4]:
x = np.arange(15)
np.set_printoptions(threshold=6)
print(x)
np.set_printoptions(threshold=1000)
print(x)

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


---------------------

**(4). An arrays of `x` and `y` , Stack the `x` and `y` arrays Horizontal.**


    Intake:
                x = np.arange(10).reshape(2,-1)

                y = np.repeat(1, 10).reshape(2,-1)

 
    
    Result:       ([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
                   [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [5]:
x = np.arange(12).reshape(2,6)
y = np.arange(16).reshape(2,8)
print(x,y, sep="\n\n")

# axis = 1
print(np.hstack((x,y)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 6,  7,  8,  9, 10, 11,  8,  9, 10, 11, 12, 13, 14, 15]])

----------------------

**(5). There are two array `x` and `y` ,output to be the matching items in both the array.**
    
    
    Intake: 
   
        x = np.array([1,2,3,2,3,4,3,4,5,6])
        y = np.array([7,2,10,2,7,4,9,4,9,8])
 
    Results:
        
         ([2, 4])
            
    

In [6]:
x = np.array([1,2,3,2,3,4,3,4,5,6])
y = np.array([7,2,10,2,7,4,9,4,9,8])
# print(len(x), len(y))

np.unique(x[np.in1d(x,y)])

array([2, 4])

---------------------

**(6). There are two array x and y ,drop the items in `X` which already exist in `Y`.**

   
    INTAKE:
     x = np.array([1,2,3,4,5])
     y = np.array([5,6,7,8,9])
    
    
    RESULT:
     ([1,2,3,4])
        
    

In [7]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])

In [8]:
mask = np.in1d(x,y)
mask

array([False, False, False, False,  True])

In [9]:
np.delete(x, np.where(mask))

array([1, 2, 3, 4])

--------------------------

**(7). Reverse the rows of a 2D array.**


    Intake : X = np.arange(9).reshape(3,3)
    
    Result :      ([[6, 7, 8],
                    [3, 4, 5],
                    [0, 1, 2]])

In [23]:
X = np.arange(9).reshape(3,3)
x = X.copy()
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
# X[ [row_list], [col_list] ]
X[[0, 2]] = X[[2, 0]]
X

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 6]])

----------------------

**(8). Reverse the columns of a 2D array.**

    Intake : X = np.arange(9).reshape(3,3)
    
    Result :     ([[2, 1, 0],
                   [5, 4, 3],
                   [8, 7, 6]])


In [26]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [13]:
x.T[[0,2]] = x.T[[2,0]]
x

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

---------------------

**(9). Print the ranks for the given numeric array `x`.**
 
   
    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=10)
    print(x)
    [ 9  4 15  0 17 16 17  8  9  0]
    
    
    Result:
    [4 2 6 0 8 7 9 3 5 1]
    

In [14]:
np.random.seed(10)
x = np.random.randint(20, size=10)
print(x)

[ 9  4 15  0 17 16 17  8  9  0]


In [15]:
# When dealing with 2D, pass an axis argument
order = x.argsort()
ranks = order.argsort()
print('Order of the matrix', order)
print('Ranks of the matrix',ranks)

Order of the matrix [3 9 1 7 0 8 2 5 4 6]
Ranks of the matrix [4 2 6 0 8 7 9 3 5 1]


In [16]:
from numpy.linalg import matrix_rank
print('Number of singular values in a matrix', matrix_rank(x))

Number of singular values in a matrix 1


--------------------

**(10). Print a rank array of the same shape as a given numeric array `x`.**


    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=[2,5])
    print(a)
    [[ 9  4 15  0 17]
    [16 17  8  9  0]]
    
    Result:
    [[4 2 6 0 8]
    [7 9 3 5 1]]

In [17]:
np.random.seed(10)
x = np.random.randint(20, size=[2,5])
print(x,x.shape)

[[ 9  4 15  0 17]
 [16 17  8  9  0]] (2, 5)


In [18]:
r, c = x.shape
# print(r,c)
order = np.argsort(x.ravel())
rank = np.argsort(order)
print(rank.reshape(r,c))

[[4 2 6 0 8]
 [7 9 3 5 1]]


In [19]:
order = np.argsort(x)
print(order)
np.argsort(order)
# order = np.argsort(x,axis=1)
# np.argsort(order,axis=1)

[[3 1 0 2 4]
 [4 2 3 0 1]]


array([[2, 1, 3, 0, 4],
       [3, 4, 1, 2, 0]], dtype=int32)

--------------------------------

**(11). Subtract the 1d array y_1d from the 2d array x_2d, such that each item of y_1d subtracts from respective row of x_2d.**
    
    Intake:
    x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
    y_1d = np.array([1,2,3])
    
    Result:
     [[2 2 2]
     [2 2 2]
     [2 2 2]]

In [20]:
x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
y_1d = np.array([1,2,3])

print(x_2d.shape)
print(y_1d.shape)

# convert sequence to matrix
x_2d - y_1d.reshape(-1,1)

(3, 3)
(3,)


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

----------------

# ----------------------------------HAPPY LEARNING--------------------------------------------------

-------------------